import { Beat } from '../lib/supabase';
import { Track } from '../data/beats';

// 9 Premium sample beats matching Supabase table structure exactly
export const PREMIUM_SAMPLE_BEATS: Beat[] = [
  {
    id: 'sample-1',
    title: 'Hyperdrive',
    artist: 'AudioForge',
    genre: 'Trap',
    bpm: 142,
    key_signature: 'C# Minor',
    price: 150,
    description: 'Heavy 808s, dark bells, and rapid hi-hat rolls. Perfect for high-energy festival bangers.',
    duration: '3:12',
    cover_gradient: 'from-orange-500 to-red-600',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 100000000).toISOString(),
    updated_at: new Date(Date.now() - 100000000).toISOString(),
  },
  {
    id: 'sample-2',
    title: 'Neon Shadows',
    artist: 'AudioForge',
    genre: 'Synthwave',
    bpm: 110,
    key_signature: 'A Minor',
    price: 220,
    description: 'Analog Juno-106 arpeggios, gated reverb snares, and driving basslines straight from 1984.',
    duration: '3:45',
    cover_gradient: 'from-purple-600 to-pink-500',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 200000000).toISOString(),
    updated_at: new Date(Date.now() - 200000000).toISOString(),
  },
  {
    id: 'sample-3',
    title: 'Vintage Velvet',
    artist: 'AudioForge',
    genre: 'Boom Bap',
    bpm: 92,
    key_signature: 'F Major',
    price: 180,
    description: 'Dusty vinyl Rhodes chords, unquantized MPC swing, and deep acoustic bass grooves.',
    duration: '2:58',
    cover_gradient: 'from-amber-600 to-yellow-700',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 300000000).toISOString(),
    updated_at: new Date(Date.now() - 300000000).toISOString(),
  },
  {
    id: 'sample-4',
    title: 'Titanium Edge',
    artist: 'AudioForge',
    genre: 'Drill',
    bpm: 144,
    key_signature: 'G Minor',
    price: 195,
    description: 'Gliding sub bass, haunting choral pads, and syncopated snare rolls designed for lyrical aggression.',
    duration: '3:20',
    cover_gradient: 'from-emerald-600 to-teal-800',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 400000000).toISOString(),
    updated_at: new Date(Date.now() - 400000000).toISOString(),
  },
  {
    id: 'sample-5',
    title: 'Midnight Rain',
    artist: 'AudioForge',
    genre: 'R&B',
    bpm: 120,
    key_signature: 'D# Minor',
    price: 170,
    description: 'Sensual guitar licks, lush ambient vocal chops, and smooth trap-infused percussion.',
    duration: '3:05',
    cover_gradient: 'from-indigo-600 to-cyan-500',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 500000000).toISOString(),
    updated_at: new Date(Date.now() - 500000000).toISOString(),
  },
  {
    id: 'sample-6',
    title: 'Dark Matter',
    artist: 'AudioForge',
    genre: 'Trap',
    bpm: 138,
    key_signature: 'B Minor',
    price: 165,
    description: 'Dark atmospheric trap with haunting melodies and hard-hitting 808s.',
    duration: '3:15',
    cover_gradient: 'from-gray-700 to-slate-900',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 600000000).toISOString(),
    updated_at: new Date(Date.now() - 600000000).toISOString(),
  },
  {
    id: 'sample-7',
    title: 'Sunset Drive',
    artist: 'AudioForge',
    genre: 'Synthwave',
    bpm: 118,
    key_signature: 'E Minor',
    price: 200,
    description: 'Cruising at sunset with lush synth pads, driving basslines, and retro drum machines.',
    duration: '4:02',
    cover_gradient: 'from-pink-500 to-orange-400',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 700000000).toISOString(),
    updated_at: new Date(Date.now() - 700000000).toISOString(),
  },
  {
    id: 'sample-8',
    title: 'Street Dreams',
    artist: 'AudioForge',
    genre: 'Boom Bap',
    bpm: 88,
    key_signature: 'C Minor',
    price: 155,
    description: 'Classic 90s hip hop feel with sampled horns, dusty drum breaks, and deep sub bass.',
    duration: '3:30',
    cover_gradient: 'from-yellow-600 to-orange-700',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 800000000).toISOString(),
    updated_at: new Date(Date.now() - 800000000).toISOString(),
  },
  {
    id: 'sample-9',
    title: 'Ice Cold',
    artist: 'AudioForge',
    genre: 'Drill',
    bpm: 150,
    key_signature: 'F# Minor',
    price: 210,
    description: 'Aggressive UK drill beat with sliding 808s, rapid hi-hats, and dark orchestral choirs.',
    duration: '2:45',
    cover_gradient: 'from-cyan-400 to-blue-600',
    audio_url: null,
    stems_url: null,
    is_sold: false,
    sold_at: null,
    created_at: new Date(Date.now() - 900000000).toISOString(),
    updated_at: new Date(Date.now() - 900000000).toISOString(),
  },
];

// Helper to convert Supabase Beat format to Checkout Track format
export const convertBeatToTrack = (beat: Beat): Track => {
  const patternMap: Record<string, 'trap' | 'synthwave' | 'boombap' | 'drill'> = {
    'Trap': 'trap',
    'Synthwave': 'synthwave',
    'Boom Bap': 'boombap',
    'Drill': 'drill',
    'R&B': 'trap'
  };

  return {
    id: beat.id,
    title: beat.title,
    artist: beat.artist || 'AudioForge',
    type: 'single',
    genre: beat.genre === 'R&B' ? 'R&B / Soul' : beat.genre,
    bpm: beat.bpm,
    key: beat.key_signature,
    price: beat.price,
    description: beat.description || '',
    includes: ['24-Bit Master WAV', 'Full Trackout Stems', 'Exclusive Ownership Rights', 'Instant Purge Guarantee'],
    duration: beat.duration || '3:00',
    stemsCount: 18,
    isSold: beat.is_sold,
    coverGradient: beat.cover_gradient || 'from-orange-500 to-red-600',
    tags: [beat.genre, `${beat.bpm} BPM`, beat.key_signature],
    synthConfig: {
      tempo: beat.bpm,
      pattern: patternMap[beat.genre] || 'trap',
      rootFreq: 130.81
    }
  };
};

export const COVER_GRADIENTS = [
  { label: 'Orange / Red (Trap)', value: 'from-orange-500 to-red-600' },
  { label: 'Purple / Pink (Synthwave)', value: 'from-purple-600 to-pink-500' },
  { label: 'Amber / Yellow (Boom Bap)', value: 'from-amber-600 to-yellow-700' },
  { label: 'Emerald / Teal (Drill)', value: 'from-emerald-600 to-teal-800' },
  { label: 'Indigo / Cyan (R&B)', value: 'from-indigo-600 to-cyan-500' },
  { label: 'Dark Slate / Gray', value: 'from-gray-700 to-slate-900' },
  { label: 'Pink / Orange', value: 'from-pink-500 to-orange-400' },
  { label: 'Cyan / Blue', value: 'from-cyan-400 to-blue-600' },
];
